### ISSUE TITLE
[elm-hot] Browser.Navigation.Key def not found. Version mismatch

### ISSUE THREAD

**Issue by sporto** [klazuka/elm-hot#12]
While trying to use elm-hot-webpack-loader I'm seeing this error

```
[elm-hot] Browser.Navigation.Key def not found. Version mismatch
```

The code seems to be looking for 
`var key = function()  ... `
https://github.com/klazuka/elm-hot/blob/master/src/inject.js#L22

If I compile my Elm module using `elm make` I cannot find that in my generated code. https://paste.ee/p/hDuYB

Thanks

**Comment by klazuka** [comment]
@sporto it looks like your version of `elm/browser` might be from one of the beta releases. The current code looks like this: https://github.com/elm/browser/blob/de28e79cf4ab17331d40ecfd4a3c592f32f9de98/src/Elm/Kernel/Browser.js#L141

Can you try `rm -rf ~/.elm` as well as your local `elm-stuff` dir and then reinstall the packages?

**Comment by sporto** [comment]
That was it, thanks
