### ISSUE TITLE
Add a "verbose" flag to enable/disable console.log

### ISSUE THREAD

**Issue by lucamug** [klazuka/elm-hot#24]
This is a minor request about adding a "verbose" flag to enable/disable the logging to the console by HMR.

I was testing the implementation of hot reload in elm-live (https://github.com/wking-io/elm-live/issues/146#issuecomment-497637785) and I have such "verbose" flag that I would also like to propagate to HMR so that the console can remain clean.

**Comment by klazuka** [comment]
If you would like to make a PR, I would be happy to review it.

**Comment by lucamug** [comment]
Hi @klazuka, this is the PR: https://github.com/klazuka/elm-hot/pull/25

**Comment by klazuka** [comment]
Fixed by #25
