### ISSUE TITLE
Do not assume that every program defines `List.map`

### ISSUE THREAD

**Issue by pdamoc** [klazuka/elm-hot#28]
Now, running `parcel` in watch mode (that starts `elm-hot`) results in the following error being thrown "Could not determine Elm version". 

`1.1.0` works fine. 

This parcel example can be used to see the error: 
https://github.com/benthepoet/elm-parcel-example

**Comment by psb** [comment]
@pdamoc I'm getting the same issue with webpack (via elm-hot-webpack-loader). I've not tried 1.1.0

**Comment by klazuka** [comment]
Thanks for the report. I wasn’t aware of the parcel integration. I’ll check it out.

**Comment by klazuka** [comment]
@pdamoc I just cloned `elm-parcel-example` and gave it a try. I had a bunch of problems getting some of the transitive node dependencies installed (`deasync`), but once I got that going, I was able to run parcel in watch node fine (`npx parcel src/index.html`) and hot reloading worked flawlessly. I don't see any errors in the console.

Can you post more details about your configuration (node, parcel, OS, Elm compiler version)?

**Comment by klazuka** [comment]
@psb the webpack loader integration works for me. Can you provide more details about your configuration (node, webpack, elm-webpack-loader, OS, Elm compiler version)?

**Comment by klazuka** [comment]
@pdamoc I was mistaken: it was doing a full page reload. 

I don't use Parcel: can you please tell me what command you mean by running it in "watch mode"? It seems like when I use `parcel watch`, it doesn't actually run a web server.

**Comment by pdamoc** [comment]
@klazuka sorry for not being careful when reporting the error. Please do the following: 

1. Download the https://github.com/benthepoet/elm-parcel-example
2. run `npm install parcel-bundler`
3. run `npx parcel src/index.html`

you should see in the console that elm-hot is being installed automatically.  

4. go to http://localhost:1234/

This sequence of commands ensures that you are running a parcel version that integrates `elm-hot` and that `elm-hot` is at its latest version.

**Comment by pdamoc** [comment]
if you go through the steps above you will have `"elm-hot": "^1.1.1",` in the `package.json`. 

If you change that to `"elm-hot": "1.1.0",` and `npm install`, you should see the app working. You might need to delete the `dist` folder but I guess that changing something in the elm file just to trigger a recompilation might have the same effect.

**Comment by psb** [comment]
@klazuka 
My `package.json`:
`{`
  `"repository": {},`
  `"license": "MIT",`
  `"scripts": {`
    `"deploy": "webpack --mode production",`
   ` "watch": "webpack --mode development --watch"`
  `},`
  `"dependencies": {`
    `"bootstrap": "^4.3.1",`
   ` "jquery": "^3.4.1",`
    `"phoenix": "file:../deps/phoenix",`
    `"phoenix_html": "file:../deps/phoenix_html",`
    `"popper.js": "^1.15.0"`
  `},`
  `"devDependencies": {`
    `"@babel/core": "^7.0.0",`
    `"@babel/preset-env": "^7.0.0",`
    `"babel-loader": "^8.0.0",`
    `"copy-webpack-plugin": "^4.5.0",`
    `"css-loader": "^2.1.1",`
    **`"elm": "^0.19.0-no-deps",`**
    **`"elm-hot-webpack-loader": "^1.1.1",`**
    **`"elm-webpack-loader": "^6.0.0",`**
    `"file-loader": "^4.1.0",`
    `"mini-css-extract-plugin": "^0.4.0",`
    `"node-sass": "^4.12.0",`
    `"optimize-css-assets-webpack-plugin": "^5.0.3",`
    `"sass-loader": "^7.1.0",`
    `"style-loader": "^0.23.1",`
    `"uglifyjs-webpack-plugin": "^1.2.4",`
   `"webpack": "4.4.0",`
    `"webpack-cli": "^3.3.5",`
    `"webpack-combine-loaders": "^2.0.4"`
  `}`
`}`

I was trying to integrate it with a Phoenix application (on macOS High Sierra (10.13.6) and using Firefox Developer Edition). My `webpack.config.js` is the same as the [example app](https://github.com/klazuka/example-elm-hot-webpack/blob/master/webpack.config.js), but it also fails if I remove the `devser` part and pass in `--hot` to webpack via the Phoenix app setup.

Maybe there is something wrong with my setup (I'm still learning Elixir and Phoenix).

I've decided not to use Elm as I need to do more native mobile development; therefore, I'm in no rush for a fix. However, let me know if you want me to try anything or need more information.

**Comment by klazuka** [comment]
@pdamoc thanks for the detailed instructions. I followed those steps and saw "installing elm-hot", and when I run the example app, HMR is working fine (I modified the example to be a simple counter using `Browser.sandbox`). I don't see any errors in the console.

Is there anything else that might be different between our two environments? The change from version 1.1.0 to 1.1.1 of elm-hot [was very small](https://github.com/klazuka/elm-hot/commit/baa708c4b77eec8f388d12a6d7348e6e40612393), but now that I look at it, it does assume that `List.map` exists in the generated code. Is it possible that your app doesn't have that?

**Comment by pdamoc** [comment]
The example I linked does not have `List.map` so, if that is working for you, the rest should work too. The project where I tripped on the issue did not have `List.map` either (it was a playground for some view code). 

I'm on `OS X 10.14.6`, `node 10.13.0` installed with `asdf`.

**Comment by psb** [comment]
@klazuka I no longer get any errors with the elm-hot-loader-plugin after actually writing some proper Elm code using the `Browser.sandbox`. Before I was just writing some minimal code without setting it up properly.

**Comment by pdamoc** [comment]
I can confirm that a `Browser.sandbox` is enough to get rid of this error. 

Adding a `List.map` to the file also fixes it. 

for example changing 

```elm 
main = Html.text "Hello"
```
 to 
```elm
main = Html.div [] (List.map Html.text ["Hello"])
```

**Comment by klazuka** [comment]
Ok. So the mistake I made was thinking that List.map would be used in all programs, which is generally true but not for toy programs. I will find a better symbol to use for the version check. 

Thanks for your help identifying the issue.
