### ISSUE TITLE
Breaks with elm/browser 1.0.2

### ISSUE THREAD

**Issue by anagrius** [klazuka/elm-hot#33]
The wait navigation keys are done seems to have changed with the elm/browser version.

![image](https://user-images.githubusercontent.com/157210/68091704-4ac36100-fe83-11e9-846a-b37be76bf955.png)

**Comment by anagrius** [comment]
Awesome. Thanks

**Comment by klazuka** [comment]
The fix is now available (elm-hot 1.1.3 and elm-hot-webpack-loader 1.1.5)

**Comment by ChristophP** [comment]
Awesome, works now. Thank you :+1:
