### ISSUE TITLE
Failing to find old key because navKeyPath changes

### ISSUE THREAD

**Issue by anagrius** [klazuka/elm-hot#35]
We have several pages in our application, the key is passed between the pages when you transition between them. Some pages store the key in e.g
```
{
    page = FooPage { navigation: { key: <KEY>, ... } }
}
```
while another page stores it in:
```
{
    page = BarPage { navKey: <KEY>, ... }
}
```

Elm-Hot fails to find the key when it wants to hot-reload. Our assumtion is that this is because the path cached in `hmr.js` is no longer correct (instance.navKeyPath) and when it tries to look it up it fails giving the error:

`keypath " + instance.navKeyPath + " is invalid. Please report a bug. `

Could you look up the key again in the oldModel when it needs to reload?

**Comment by klazuka** [comment]
A few people have run into this, so I fixed it just now. The fix actually makes the code simpler. Thanks for bringing this to my attention.

**Comment by klazuka** [comment]
I published the fix to npm just now
