### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by Punie** [klazuka/elm-hot#4]
Hi there, I've been starting to use elm-hot to work on the 0.19 upgrade of my project by referencing your repo in my package.json.

Are there any major issue left prior to the release on npm that I should be aware of ? I am well aware that elm-hot is in its early stages still.

Anyway, thank you for the amazing work. The (very-limited) tests I did so far did work well enough !

**Comment by klazuka** [comment]
I've been holding off on formally releasing it until [elm-webpack-loader supports 0.19](https://github.com/elm-community/elm-webpack-loader/pull/142) is merged and published.

**Comment by klazuka** [comment]
@Punie I published it last night under the name [elm-hot-webpack-loader](https://www.npmjs.com/package/elm-hot-webpack-loader). You can get it from the npm repository now (it still depends on the fork PR for elm-webpack-loader, but hopefully that will be landing soon).
