### ISSUE TITLE
Error "Cannot read property 'hasOwnProperty' of undefined"

### ISSUE THREAD

**Issue by lucamug** [klazuka/elm-hot#40]
I am getting this error if I activate the hot reload using elm-live. It is unclear to me if the error is related to `elm-live` implementation or to `elm-hot`.

I commented to a related issue in elm-live here: https://github.com/wking-io/elm-live/issues/211

This is the error:

```
elm.js:37126 Uncaught TypeError: Cannot read property 'hasOwnProperty' of undefined
    at findNavKey (elm.js:37126)
    at hookedInit (elm.js:37218)
    at _Platform_initialize (elm.js:1978)
    at _Platform_initialize (elm.js:37256)
    at elm.js:4093
    at elm.js:20
    at Object.module.init (elm.js:36980)
    at index-hot.html:29
```

<img width="826" alt="Screen Shot 2020-01-31 at 9 34 47" src="https://user-images.githubusercontent.com/5551094/73502804-8ed7ea80-440d-11ea-8b25-adf7a24ff27e.png">

<img width="595" alt="Screen Shot 2020-01-31 at 9 34 30" src="https://user-images.githubusercontent.com/5551094/73502805-8ed7ea80-440d-11ea-814b-66b50a7d46f7.png">

**Comment by klazuka** [comment]
You need to upgrade elm-hot to version 1.1.4 which includes a bugfix related to changes in how the Elm debugger is implemented.

Unfortunately elm-live's `package.json` pins elm-hot to version 1.1.1
