### ISSUE TITLE
Small conflict with elm-optimize-level-2

### ISSUE THREAD

**Issue by ianmackenzie** [klazuka/elm-hot#48]
I've been experimenting with [`elm-optimize-level-2`](https://github.com/mdgriffith/elm-optimize-level-2) in our Parcel build (a large part of what I do is testing performance impact of code changes, so it's useful to be able to combine hot reloading with an optimized-but-not-minified build so I can make a change and get a quick sense of whether things are faster or slower). Unfortunately there's a small conflict between `elm-optimize-level-2` and `elm-hot`; `elm-hot` expects the exact string

```js
var key = function() { key.a(onUrlChange(_Browser_getUrl())); };
```

in the output, but the output from `elm-optimize-level-2` has

```js
var key = function () { key.a(onUrlChange(_Browser_getUrl())); };
```

(with a space between `function` and `()`). For now I have a little post-processing script that makes the necessary replacement, but would it make sense to use a whitespace-tolerant regex instead of an exact string match on [this line](https://github.com/klazuka/elm-hot/blob/efe9db967496415944246006b4e711c0aed1e777/src/inject.js#L22)?

**Comment by klazuka** [comment]
yeah, that makes sense. Go for it
