### ISSUE TITLE
Browser.element broken for certain DOM configurations

### ISSUE THREAD

**Issue by klazuka** [klazuka/elm-hot#9]
littlestudent on Slack wrote that HMR is broken for him with `Browser.element`

HMR fails to show the new changes with this DOM:
```
<body>
  <div id="root" class="fullHeight"></div>
</body>
```

but works with:

```
<body>
  <div>
    <div id="root" class="fullHeight"></div>
  </div>
</body>
```

**Comment by littleStudent** [comment]
Hi, I reported that issue in slack. If you need any more information on the setup i am happy to help figure this out.

**Comment by klazuka** [comment]
I'm going to close this due to lack of activity. Please re-open if necessary.
